### ISSUE TITLE
feature: add simple eth chain

### ISSUE THREAD

**Issue by Anmol1696** [hyperweb-io/starship#591]
Add ability to have simple eth chain setup with Starship

**Comment by Anmol1696** [comment]
How best to expose the eth chain to the config file.
We have a couple of options:

## Option 1:
```yaml
chains:
- id: becon-chain-1337
  name: eth-becon-chain
  numValidators: 4  # number of nodes
  config:
  #  ... 
  balances: 
    - address: <eth addr>
      amount: 1000ETH
    # ...
- id: execution-chain
  name: eth-execution-chain
  image: prysm:stable
  numValidators: 4  # number of nodes for execution chain
- id: validator
  name: eth-validator
  numValidator: 4   # number of validators      
```

Each type of node has its own 

## Option 2:
```yaml
chains:
- id: eth
  name: ethereum
  numValidators: 4
  config: 
    beaconChain:
      image:
    executionChain:
      image:
    validator:
      image:
```
In this case we will have a single stateful set with 3 containers, one for each type of node.
This way number of nodes or numValidators is just a replica of the same set of nodes.

## Option 3:
Similar to 2, but we will have different stateful set for each of the chain.
