### ISSUE TITLE
Custom port forwarding

### ISSUE THREAD

**Issue by Anmol1696** [hyperweb-io/starship#693]
Sometimes, people need to expose custom ports themselves.

Instead of increasing the ports list or dir, we could have a section for custom ports, like:

## Option 1
```
chains:
  - id: osmosis-1
    name: osmosis
    ports:
      rpc: 2657
      custom:
        - name: eth-http-jsonrpc
          target: 8467
          port: 8467
```

## Option 2:
```
chains:
  - id: osmosis-1
    name: osmosis
    ports:
      rpc: 2657
    customPorts:
      - name: eth-http-jsonrpc
        target: 8467
        port: 8467
```

Custom ports could be more open ended, and anything from a service can be opened up with custom ports.
